Upstreamify dl-everythinh (#1989)
* Force avoiding the UI extraction, thanks GBOARD

* Dynamic loader for EGL

* Update egl_bridge.c

* Fix a bunch of very silly errors - it works now!

* Forgot to add breaks - zink should work again

* Simplify TouchCharInput constructors

* CI: Update gl4es

* Fixes #1977

java.lang.NullPointerException: Attempt to get length of null array
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:114)
	at com.kdt.pickafile.FileListView.init(FileListView.java:93)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:52)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:46)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:36)
	at net.kdt.pojavlaunch.CustomControlsActivity.load(CustomControlsActivity.java:215)
	at net.kdt.pojavlaunch.MainActivity.lambda$onCreate$0(MainActivity.java:30)
	at net.kdt.pojavlaunch.-$$Lambda$MainActivity$ikMCYDL-Y9h7UKXuTvp9oMxZ-SU.onNavigationItemSelected(Unknown Source:0)
	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
	at android.view.View.performClick(View.java:7277)
	at android.view.View.performClickInternal(View.java:7254)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27916)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Co-authored-by: SerpentSpirale <mathiasboulay@free.fr>
Co-authored-by: github-actions <github-actions@users.noreply.github.com>
Co-authored-by: Duy Tran Khanh <40482367+khanhduytran0@users.noreply.github.com>